---
# tasks file for ansible-role-gradle

- name: "Check if gradle is present"
  stat:
    path: "{{ gradle_link }}"
  register: gradle_present

- name: "Check gradle version is present"
  shell: "{{ gradle_link }} -v | grep -F {{ gradle_version }}"
  changed_when: False
  ignore_errors: true
  register: gradle_version_check
  check_mode: no
  when: gradle_present.stat.exists

- block:
  - name: "Install unzip"
    package:
      name: unzip
      state: present

  - name: "Download"
    get_url:
      url: "{{ gradle_download_url }}"
      dest: "{{ gradle_download }}"
      checksum: "{{ gradle_checksum }}"

  - name: "Extract Gradle {{ gradle_version }}"
    unarchive:
      src: "{{ gradle_download }}"
      dest: "{{ gradle_base_dir }}"
      remote_src: True

  - name: "Add gradle symlink to path"
    file:
      src: "{{ gradle_base_dir }}/{{ gradle_extract_dir }}/bin/gradle"
      dest: "{{ gradle_link }}"
      owner: root
      group: root
      state: link

  - name: "Validate Gradle version"
    shell: "{{ gradle_link }} -v | grep -F {{ gradle_version }}"
    failed_when: false
    ignore_errors: true
    register: gradle_ver
    check_mode: no

  - fail:
      msg: "Seems to be gradle {{ gradle_version }} is missing ... aborting"
    when: gradle_ver.rc != 0

  when:  gradle_version not in gradle_version_check.stdout
